#!/bin/sh
# Ютуб в подкоп

clear
echo "v0.2"

# Проверяем наличие подкопа в системе и его версию
PACKAGE="podkop"
PODKOP_VERSION=0

# Получаем версию установленного пакета (пусто если не установлен)
PODKOP_VERSION=$(opkg list-installed | grep "^$PACKAGE " | awk '{print $3}')
# Выделяем мажорную версию
PODKOP_VERSION=$(echo "$PODKOP_VERSION" | cut -d '.' -f 1-2)

if [ -z "$PODKOP_VERSION" ]; then
	echo -e "\033[33m
	PODKOP НЕ УСТАНОВЛЕН!
	УСТАНОВИТЕ СКРИПТ ИЗ ЗАКРЕПА \"ИНТЕРНЕТ БЕЗ ГРАНИЦ\" - https://t.me/routerich/3845\033[0m"
	exit 1
fi

if [ -n "$PODKOP_VERSION" ] && echo "$PODKOP_VERSION" | grep -q -E "v0\.[67]"; then
    echo -e "\033[32mВерсия пакета $PACKAGE: "$PODKOP_VERSION"\033[0m"
else
	echo -e "\033[33mУстановленная версия пакета $PACKAGE ($PODKOP_VERSION) не актуальна\033[0m"
	echo -e "\033[33mРекомендуется обновить $PACKAGE до версии v0.6 или v0.7\033[0m"
	exit 1		
fi
sleep 3
clear

CONFIG_FILE="/etc/config/podkop"
# Проверяем существование файла
if [ ! -f "$CONFIG_FILE" ]; then
    echo "Ошибка: Файл $CONFIG_FILE не существует"
    exit 1
fi

SERVICES_STOP="podkop youtubeUnblock zapret"
SERVICES_START="podkop youtubeUnblock"

# echo "$PODKOP_VERSION"
for service in $SERVICES_STOP; do
  service $service stop >/dev/null 2>&1
  service $service disable >/dev/null 2>&1
done
sleep 1

echo
echo "Добавляем Ютуб в подкоп"

# Создаем backup
# cp "$CONFIG_FILE" "${CONFIG_FILE}.backup.$(date +%Y%m%d_%H%M%S)"
# echo "Создан backup: ${CONFIG_FILE}.backup.$(date +%Y%m%d_%H%M%S)"

# Удаляем все list community_lists 'youtube'
sed -i '/[[:space:]]*list community_lists '\''youtube'\''/d' "$CONFIG_FILE" >/dev/null 2>&1

# Подсчитываем количество секций config
count=$(grep -c '^config' "$CONFIG_FILE")
section_name=""
# Получаем имя секции и активируем листы  сообщества
if [ $count -gt 1 ]; then
		 target_section=$(grep '^config' "$CONFIG_FILE" | awk 'NR==2 {print $0; exit}')
		 section_name=$(echo "$target_section" | sed "s/.*'\([^']*\)'.*/\1/")
	elif [ $count -eq 1 ]; then
	     target_section=$(grep '^config' "$CONFIG_FILE")
		 section_name=$(echo "$target_section" | sed "s/.*'\([^']*\)'.*/\1/")
	else
	     echo "Секций в "${CONFIG_FILE}" не найдено"
fi

if [ -n target_section ]; then
	uci set podkop.${section_name}.community_lists_enabled='1'
	uci set podkop.${section_name}.community_lists='youtube'
	uci commit
fi
# Заменяем строку с секцией на саму себя + list community_lists 'youtube'
sed -i "/^${target_section}/a\\\tlist community_lists 'youtube'" "$CONFIG_FILE"

# Проверяем добавление нового параметра в $CONFIG_FILE
# if ! grep -q "list community_lists 'youtube'" /etc/config/podkop; then
  # echo "Не удалось добавить параметр, прекращаю работу"
  # service podkop restart >/dev/null 2>&1
  # service podkop enable >/dev/null 2>&1
  # exit 1
# fi

echo "Готово! Добавлено в секцию: $target_section"
echo

service podkop restart >/dev/null 2>&1
service podkop enable >/dev/null 2>&1
echo

echo "РОУТЕР ПЕРЕЗАГРУЗИТСЯ ЧЕРЕЗ 10 СЕКУНД!"
sleep 10
reboot

exit 0
