#!/bin/sh
# Селектор стратегий для youtubeUnblock 

clear
echo "Селектор стратегий для youtubeUnblock v0.2"

# Проверяем наличие в системе подкопа
PACKAGE="podkop"
REQUIRED_VERSION="v0.7"
PODKOP_NI=0
# Получаем информацию об установленном пакете
INSTALLED_INFO=$(opkg list-installed | grep "^$PACKAGE ")
if [ -z "$INSTALLED_INFO" ]; then 
	PODKOP_NI=1 
	echo
	echo -e "\033[33mPodkop не установлен, часть функций недоступна\033[0m"
else
	# Извлекаем версию подкопа
	VERSION=$(echo "$INSTALLED_INFO" | awk '{print $3}')
	# Проверяем, содержит ли версия требуемую подстроку
	if echo "$VERSION" | grep -q "$REQUIRED_VERSION"; then
		echo -e "\033[32mВерсия пакета $PACKAGE: $VERSION\033[0m"
	else
		echo -e "\033[33mУстановленная версия пакета $PACKAGE не актуальна\033[0m"
		echo -e "\033[33mРекомендуется обновить $PACKAGE до последней версии\033[0m"
		echo -e "\033[33mЧасть функций недоступна\033[0m"
		PODKOP_NI=1
	fi
fi

sleep 5

# Проверяем наличия в системе необходимых для работы пакетов
TARGET_PKGS="youtubeUnblock luci-app-youtubeUnblock zapret luci-app-zapret"

for pkg in $TARGET_PKGS; do
	# opkg list-installed выводит "имя - версия"
	# grep ищет строку, начинающуюся (^) с имени пакета
	if ! opkg list-installed "$pkg" | grep -q "^$pkg"; then
		# Устанавливаем вебфейс анблока итп.
		echo "Устанавливаем youtubeUnblock luci-app-youtubeUnblock zapret luci-app-zapret"
		echo "====="
		opkg update
		opkg install youtubeUnblock luci-app-youtubeUnblock zapret luci-app-zapret
		sleep 1
		break
	fi
done

main() {
	# Бэкапим конфигу
	echo "Создаём архивную копию конфигурации в файле /tempbackup.tar.gz"
	# echo "====="
	[ -f /tempbackup.tar.gz ] && echo "Архив /tempbackup.tar.gz уже существует" || \
	{ sysupgrade -b /tempbackup.tar.gz && echo "Архив /tempbackup.tar.gz создан"; }
	echo
	
	# Останавливаем сервисы
    service zapret stop >/dev/null 2>&1
	service zapret disable >/dev/null 2>&1
	service youtubeUnblock stop >/dev/null 2>&1
	service youtubeUnblock disable >/dev/null 2>&1
	service podkop stop >/dev/null 2>&1
	sleep 1	

	# Удаляем все list community_lists 'youtube' из подкопа
	if [ "$PODKOP_NI" -ne 1 ]; then 
		if [ -f "/etc/config/podkop" ]; then 
			sed -i '/[[:space:]]*list community_lists '\''youtube'\''/d' "/etc/config/podkop"
		fi
	fi
	# Удаляем секцию YouTube из ЮАБ

	sleep 1

	# Создаём новую секцию YouTube
	echo "Создаём новую секцию YouTube"
	echo "${SELECTED_STRATEGY}" >>/etc/config/youtubeUnblock
	echo "${URLS}" >>/etc/config/youtubeUnblock
	sleep 1

	case "$idx" in
		1)
			# Стратегия по умолчанию
			# Получаем индекс секции YouTube
			SECTION=$(uci show youtubeUnblock | grep "name='YouTube'" | cut -d. -f2)
			# echo "${SECTION}"
			# Переносим секцию YouTube на первую позицию списка
			uci reorder youtubeUnblock.${SECTION}=1
			uci commit
			sleep 1
		;;
	esac
	
	service podkop start >/dev/null 2>&1
	service podkop enable >/dev/null 2>&1
	service youtubeUnblock enable >/dev/null 2>&1
	service youtubeUnblock start >/dev/null 2>&1
}

u_section_delete() {

	# Меняем конфиг ЮАБ на конфиг от zapret и правим настройки
	# Удаляем секцию YouTube
	# uci delete youtubeUnblock.$(uci show youtubeUnblock | grep "name='YouTube'" | cut -d. -f2) && uci commit
	section_id=$(uci show youtubeUnblock | grep "name='YouTube'" | cut -d. -f2)

	# Проверяем, что section_id не пустой
	if [ -n "$section_id" ]; then
		echo "Удаляем секцию YouTube: $section_id"
		uci delete youtubeUnblock.$section_id
		sleep 1
		uci commit
	else
		echo "Секция YouTube не найдена"
	fi
}




# Объявляем и инициализируем переменные
# Стратегия по умолчанию
STRATEGY_1="config section
	option name 'YouTube'
	option enabled '1'
	option tls_enabled '1'
	option fake_sni '1'
	option faking_strategy 'pastseq'
	option fake_sni_seq_len '1'
	option fake_sni_type 'default'
	option frag 'tcp'
	option frag_sni_reverse '1'
	option frag_sni_faked '0'
	option frag_middle_sni '1'
	option frag_sni_pos '1'
	option seg2delay '0'
	option fk_winsize '0'
	option synfake '0'
	option sni_detection 'parse'
	option all_domains '0'
	option quic_drop '0'
	option udp_mode 'fake'
	option udp_fake_seq_len '6'
	option udp_fake_len '64'
	option udp_filter_quic 'disabled'
	option udp_faking_strategy 'none'"


STRATEGY_2="config section
	option name 'YouTube'
	option enabled '1'
	option tls_enabled '1'
	option fake_sni '0'
	option faking_strategy 'pastseq'
	option fake_sni_seq_len '1'
	option fake_sni_type 'default'
	option frag 'tcp'
	option frag_sni_reverse '1'
	option frag_sni_faked '0'
	option frag_middle_sni '1'
	option frag_sni_pos '1'
	option seg2delay '0'
	option fk_winsize '0'
	option synfake '0'
	option sni_detection 'parse'
	option all_domains '0'
	option quic_drop '0'
	option udp_mode 'fake'
	option udp_fake_seq_len '6'
	option udp_fake_len '64'
	option udp_filter_quic 'disabled'
	option udp_faking_strategy 'none'"
	
STRATEGY_3="config section
	option name 'YouTube'
	option enabled '1'
	option tls_enabled '1'
	option fake_sni '0'
	option faking_strategy 'pastseq'
	option fake_sni_seq_len '1'
	option fake_sni_type 'default'
	option frag 'tcp'
	option frag_sni_reverse '1'
	option frag_sni_faked '0'
	option frag_middle_sni '1'
	option frag_sni_pos '1'
	option seg2delay '0'
	option fk_winsize '0'
	option synfake '0'
	option sni_detection 'parse'
	option all_domains '0'
	option quic_drop '1'
	option udp_mode 'fake'
	option udp_fake_seq_len '6'
	option udp_fake_len '64'
	option udp_filter_quic 'disabled'
	option udp_faking_strategy 'none'"

STRATEGY_4="config section
	option name 'YouTube'
	option tls_enabled '1'
	option fake_sni '1'
	option faking_strategy 'pastseq'
	option fake_sni_seq_len '5'
	option fake_sni_type 'random'
	option frag 'tcp'
	option seg2delay '3'
	option synfake '0'
	option all_domains '0'
	option sni_detection 'parse'
	option quic_drop '1'
	option enabled '1'
	option frag_sni_reverse '1'
	option frag_sni_faked '0'
	option frag_middle_sni '1'
	option frag_sni_pos '1'
	option fk_winsize '0'"
	
STRATEGY_5="config section
	option name 'YouTube'
	option enabled '1'
	option tls_enabled '1'
	option fake_sni '1'
	option faking_strategy 'randseq'
	option fake_sni_seq_len '5'
	option fake_sni_type 'default'
	option frag 'ip'
	option seg2delay '3'
	option synfake '0'
	option sni_detection 'parse'
	option all_domains '0'
	option quic_drop '0'
	option udp_mode 'fake'
	option udp_fake_seq_len '6'
	option udp_fake_len '64'
	option udp_filter_quic 'all'
	option udp_faking_strategy 'none'
	option udp_stun_filter '0'"
	
STRATEGY_6="config section
	option name 'YouTube'
	option enabled '1'
	option tls_enabled '1'
	option fake_sni '1'
	option faking_strategy 'randseq'
	option fake_sni_seq_len '2'
	option fake_sni_type 'default'
	option frag 'tcp'
	option seg2delay '0'
	option synfake '0'
	option sni_detection 'parse'
	option all_domains '0'
	option quic_drop '0'
	option udp_mode 'fake'
	option udp_fake_seq_len '6'
	option udp_fake_len '64'
	option udp_filter_quic 'all'
	option udp_faking_strategy 'none'
	option udp_stun_filter '0'
	option fake_seq_offset '0'
	option frag_sni_reverse '1'
	option frag_sni_faked '0'
	option frag_middle_sni '1'
	option frag_sni_pos '1'
	option fk_winsize '0'"
  
STRATEGY_7="config section
	option name 'YouTube'
	option enabled '1'
	option tls_enabled '1'
	option fake_sni '1'
	option faking_strategy 'tcp_check'
	option fake_sni_seq_len '1'
	option fake_sni_type 'random'
	option frag 'tcp'
	option frag_sni_reverse '1'
	option frag_sni_faked '0'
	option frag_middle_sni '1'
	option frag_sni_pos '1'
	option seg2delay '3'
	option fk_winsize '0'
	option synfake '0'
	option sni_detection 'parse'
	option all_domains '0'
	option quic_drop '0'
	option udp_mode 'fake'
	option udp_fake_seq_len '6'
	option udp_fake_len '64'
	option udp_filter_quic 'all'
	option udp_faking_strategy 'none'
	option udp_stun_filter '0'"
	
STRATEGY_8="config section
	option name 'YouTube'
	option enabled '1'
	option tls_enabled '1'
	option fake_sni '1'
	option faking_strategy 'tcp_check'
	option fake_sni_seq_len '1'
	option fake_sni_type 'default'
	option frag 'none'
	option seg2delay '0'
	option synfake '0'
	option sni_detection 'parse'
	option all_domains '0'
	option quic_drop '0'
	option udp_mode 'fake'
	option udp_fake_seq_len '6'
	option udp_fake_len '64'
	option udp_filter_quic 'all'
	option udp_faking_strategy 'none'
	option udp_stun_filter '0'"
	

URLS="	list sni_domains 'googlevideo.com'
	list sni_domains 'youtubei.googleapis.com'
	list sni_domains 'ytimg.com'
	list sni_domains 'yt3.ggpht.com'
	list sni_domains 'yt4.ggpht.com'
	list sni_domains 'youtube.com'
	list sni_domains 'youtubeembeddedplayer.googleapis.com'
	list sni_domains 'ytimg.l.google.com'
	list sni_domains 'jnn-pa.googleapis.com'
	list sni_domains 'youtube-nocookie.com'
	list sni_domains 'youtube-ui.l.google.com'
	list sni_domains 'yt-video-upload.l.google.com'
	list sni_domains 'wide-youtube.l.google.com'
	list sni_domains 'youtu.be'
	list sni_domains 'youtube.googleapis.com'
	list sni_domains 'yt.be'
	list sni_domains 'withyoutube.com'
	list sni_domains 'youtubeeducation.com'
	list sni_domains 'youtubefanfest.com'
	list sni_domains 'youtubegaming.com'
	list sni_domains 'youtubekids.com'
	list sni_domains 'youtubemobilesupport.com'
	list sni_domains 'youtube.ae'
	list sni_domains 'youtube.al'
	list sni_domains 'youtube.am'
	list sni_domains 'youtube.at'
	list sni_domains 'youtube.az'
	list sni_domains 'youtube.ba'
	list sni_domains 'youtube.be'
	list sni_domains 'youtube.bg'
	list sni_domains 'youtube.bh'
	list sni_domains 'youtube.bo'
	list sni_domains 'youtube.by'
	list sni_domains 'youtube.ca'
	list sni_domains 'youtube.cat'
	list sni_domains 'youtube.ch'
	list sni_domains 'youtube.cl'
	list sni_domains 'youtube.co'
	list sni_domains 'youtube.co.ae'
	list sni_domains 'youtube.co.at'
	list sni_domains 'youtube.co.cr'
	list sni_domains 'youtube.co.hu'
	list sni_domains 'youtube.co.id'
	list sni_domains 'youtube.co.il'
	list sni_domains 'youtube.co.in'
	list sni_domains 'youtube.co.jp'
	list sni_domains 'youtube.co.ke'
	list sni_domains 'youtube.co.kr'
	list sni_domains 'youtube.co.ma'
	list sni_domains 'youtube.co.nz'
	list sni_domains 'youtube.co.th'
	list sni_domains 'youtube.co.tz'
	list sni_domains 'youtube.co.ug'
	list sni_domains 'youtube.co.uk'
	list sni_domains 'youtube.co.ve'
	list sni_domains 'youtube.co.za'
	list sni_domains 'youtube.co.zw'
	list sni_domains 'youtube.com.ar'
	list sni_domains 'youtube.com.au'
	list sni_domains 'youtube.com.az'
	list sni_domains 'youtube.com.bd'
	list sni_domains 'youtube.com.bh'
	list sni_domains 'youtube.com.bo'
	list sni_domains 'youtube.com.br'
	list sni_domains 'youtube.com.by'
	list sni_domains 'youtube.com.co'
	list sni_domains 'youtube.com.do'
	list sni_domains 'youtube.com.ec'
	list sni_domains 'youtube.com.ee'
	list sni_domains 'youtube.com.eg'
	list sni_domains 'youtube.com.es'
	list sni_domains 'youtube.com.gh'
	list sni_domains 'youtube.com.gr'
	list sni_domains 'youtube.com.gt'
	list sni_domains 'youtube.com.hk'
	list sni_domains 'youtube.com.hn'
	list sni_domains 'youtube.com.hr'
	list sni_domains 'youtube.com.jm'
	list sni_domains 'youtube.com.jo'
	list sni_domains 'youtube.com.kw'
	list sni_domains 'youtube.com.lb'
	list sni_domains 'youtube.com.lv'
	list sni_domains 'youtube.com.ly'
	list sni_domains 'youtube.com.mk'
	list sni_domains 'youtube.com.mt'
	list sni_domains 'youtube.com.mx'
	list sni_domains 'youtube.com.my'
	list sni_domains 'youtube.com.ng'
	list sni_domains 'youtube.com.ni'
	list sni_domains 'youtube.com.om'
	list sni_domains 'youtube.com.pa'
	list sni_domains 'youtube.com.pe'
	list sni_domains 'youtube.com.ph'
	list sni_domains 'youtube.com.pk'
	list sni_domains 'youtube.com.pt'
	list sni_domains 'youtube.com.py'
	list sni_domains 'youtube.com.qa'
	list sni_domains 'youtube.com.ro'
	list sni_domains 'youtube.com.sa'
	list sni_domains 'youtube.com.sg'
	list sni_domains 'youtube.com.sv'
	list sni_domains 'youtube.com.tn'
	list sni_domains 'youtube.com.tr'
	list sni_domains 'youtube.com.tw'
	list sni_domains 'youtube.com.ua'
	list sni_domains 'youtube.com.uy'
	list sni_domains 'youtube.com.ve'
	list sni_domains 'youtube.cr'
	list sni_domains 'youtube.cz'
	list sni_domains 'youtube.de'
	list sni_domains 'youtube.dk'
	list sni_domains 'youtube.ee'
	list sni_domains 'youtube.es'
	list sni_domains 'youtube.fi'
	list sni_domains 'youtube.fr'
	list sni_domains 'youtube.ge'
	list sni_domains 'youtube.gr'
	list sni_domains 'youtube.gt'
	list sni_domains 'youtube.hk'
	list sni_domains 'youtube.hr'
	list sni_domains 'youtube.hu'
	list sni_domains 'youtube.ie'
	list sni_domains 'youtube.in'
	list sni_domains 'youtube.iq'
	list sni_domains 'youtube.is'
	list sni_domains 'youtube.it'
	list sni_domains 'youtube.jo'
	list sni_domains 'youtube.jp'
	list sni_domains 'youtube.kr'
	list sni_domains 'youtube.kz'
	list sni_domains 'youtube.la'
	list sni_domains 'youtube.lk'
	list sni_domains 'youtube.lt'
	list sni_domains 'youtube.lu'
	list sni_domains 'youtube.lv'
	list sni_domains 'youtube.ly'
	list sni_domains 'youtube.ma'
	list sni_domains 'youtube.md'
	list sni_domains 'youtube.me'
	list sni_domains 'youtube.mk'
	list sni_domains 'youtube.mn'
	list sni_domains 'youtube.mx'
	list sni_domains 'youtube.my'
	list sni_domains 'youtube.ng'
	list sni_domains 'youtube.ni'
	list sni_domains 'youtube.nl'
	list sni_domains 'youtube.no'
	list sni_domains 'youtube.pa'
	list sni_domains 'youtube.pe'
	list sni_domains 'youtube.ph'
	list sni_domains 'youtube.pk'
	list sni_domains 'youtube.pl'
	list sni_domains 'youtube.pr'
	list sni_domains 'youtube.pt'
	list sni_domains 'youtube.qa'
	list sni_domains 'youtube.ro'
	list sni_domains 'youtube.rs'
	list sni_domains 'youtube.ru'
	list sni_domains 'youtube.sa'
	list sni_domains 'youtube.se'
	list sni_domains 'youtube.sg'
	list sni_domains 'youtube.si'
	list sni_domains 'youtube.sk'
	list sni_domains 'youtube.sn'
	list sni_domains 'youtube.soy'
	list sni_domains 'youtube.sv'
	list sni_domains 'youtube.tn'
	list sni_domains 'youtube.tv'
	list sni_domains 'youtube.ua'
	list sni_domains 'youtube.ug'
	list sni_domains 'youtube.uy'
	list sni_domains 'youtube.vn'
	list sni_domains 'youtubego.co.id'
	list sni_domains 'youtubego.co.in'
	list sni_domains 'youtubego.com'
	list sni_domains 'youtubego.com.br'
	list sni_domains 'youtubego.id'
	list sni_domains 'youtubego.in'"

echo
echo "ПРОВЕРЯЙТЕ ДОСТУП К ЮТУБ"
echo

while true; do

clear

# Выбор стратегии
echo "
	
Выберите стратегию:

 1 - Стратегия по умолчанию (из коробки)
 
 2 - Стратегия pastseq_1
 3 - Стратегия pastseq_2
 4 - Стратегия pastseq_3
 5 - Стратегия randseq_1
 6 - Стратегия randseq_2
 7 - Стратегия tcp_check_1
 8 - Стратегия tcp_check_2
 "
if [ "$PODKOP_NI" -ne 1 ]; then echo " 9 - Ничего не помогло. Хочу ютуб через podkop!"; fi
echo " 0 - Выход
"


	printf "Введите номер выбранной стратегии > "
	read idx
	echo

	case "$idx" in
		0)
			# Если пользователь ввел 0 — выходим без ошибки
			echo "Выход..."
			echo
			exit 0 
			;;
#		''|*[!0-9]*) 
#			# Проверка на "не число" или пустоту
#			echo "Ошибка: введите номер стратегии"; exit 1 
#			;;
		 9)  	
			 if [ "$PODKOP_NI" -ne 1 ]; then
			 	 service zapret stop >/dev/null 2>&1
				 service zapret disable >/dev/null 2>&1
				 service youtubeUnblock stop >/dev/null 2>&1
				 service youtubeUnblock disable >/dev/null 2>&1
				 sleep 1
				 u_section_delete
				 sh <(wget -qO- https://raw.githubusercontent.com/kkkkCampbell/trash/refs/heads/uttoobe/u_to_podkop)
				 exit 0
			 fi
		;;
		*) 
			# Все остальные варианты (числа 1, 2, 3...9)
				if echo "$idx" | grep -qE '^[0-9]$'; then
					eval "SELECTED_STRATEGY=\$STRATEGY_$idx"
					main

					sleep 5

					echo
					echo "ПРОВЕРЯЙТЕ ДОСТУП К ЮТУБ"
					echo
					echo "Выбрана стратегия №" "$idx"
					printf "ЕСЛИ СТРАТЕГИЯ СРАБОТАЛА ВВЕДИТЕ 1, ЕСЛИ НЕТ 0 > "
					read strat_working

					if [ "$strat_working" = "1" ]; then
						echo "Успех! Завершаем работу."
						echo
						exit 0
					fi
				fi
			;;
	esac
done

exit 0
