#!/bin/sh
# Селектор стратегий для youtubeUnblock 
# You_Tu_be!

# Бэкапим конфигу
echo "Создаём архивную копию конфигурации в файле /tempbackup.tar.gz"
# echo "====="
[ -f /tempbackup.tar.gz ] && echo "Архив /tempbackup.tar.gz уже существует" || \
{ sysupgrade -b /tempbackup.tar.gz && echo "Архив /tempbackup.tar.gz создан"; }

clear
echo "Селектор стратегий для youtubeUnblock v0.2.1"

# Проверяем версию подкопа
PACKAGE="podkop"
PODKOP_VERSION=0
CONFIG_FILE="/etc/config/podkop"
# Получаем версию установленного пакета (будет пустой строкой если не установлен)
PODKOP_VERSION=$(opkg list-installed | grep "^$PACKAGE " | awk '{print $3}')
# Выделяем мажорную версию
PODKOP_VERSION=$(echo "$PODKOP_VERSION" | cut -d '.' -f 1-2)

if [ -n "$PODKOP_VERSION" ] && echo "$PODKOP_VERSION" | grep -q -E "v0\.[7]"; then
    echo -e "\033[32mВерсия пакета $PACKAGE: "$PODKOP_VERSION"\033[0m"
else
    if [ -z "$PODKOP_VERSION" ]; then
        echo -e "\033[33mPodkop не установлен, часть функций недоступна\033[0m"
		PODKOP_VERSION=""
		sleep 3
    else
        echo -e "\033[33mУстановленная версия пакета $PACKAGE ($PODKOP_VERSION) не актуальна\033[0m"
        echo -e "\033[33mРекомендуется обновить $PACKAGE до версии v0.7\033[0m"
		echo -e "\033[33mЧасть функций недоступна.\033[0m"
		PODKOP_VERSION=""
		sleep 8
    fi
fi

sleep 5

# Проверяем наличие в системе необходимых для работы пакетов
TARGET_PKGS="youtubeUnblock luci-app-youtubeUnblock"
# zapret luci-app-zapret"

for pkg in $TARGET_PKGS; do
	# opkg list-installed выводит "имя - версия"
	# grep ищет строку, начинающуюся (^) с имени пакета
	if ! opkg list-installed "$pkg" | grep -q "^$pkg"; then
		# Устанавливаем вебфейс анблока итп.
		echo "Устанавливаем youtubeUnblock luci-app-youtubeUnblock"
		#zapret luci-app-zapret"
		echo "====="
		opkg update
		opkg install youtubeUnblock luci-app-youtubeUnblock
 		#zapret luci-app-zapret
		sleep 1
		break
	fi
done

SERVICES_STOP="podkop youtubeUnblock zapret"
SERVICES_START="podkop youtubeUnblock"

main() {

	# Останавливаем сервисы
	echo "Останавливаем сервисы"
	for service in $SERVICES_STOP; do
	  service $service stop >/dev/null 2>&1
	  service $service disable >/dev/null 2>&1
	done
	sleep 1

	# # Удаляем все list community_lists 'youtube' и option community_lists 'youtube'
	if [ -n "$PODKOP_VERSION" ]; then 
		if [ -f "/etc/config/podkop" ]; then 
			sed -i '/list community_lists '\''youtube'\''/d' "${CONFIG_FILE}"
			sed -i '/option community_lists '\''youtube'\''/d' "${CONFIG_FILE}"
		fi
	fi
	
	# Удаляем секцию YouTube из ЮАБ
	echo "Ищем секцию YouTube в youtubeUnblock"
	u_section_delete
	sleep 1

	# Создаём новую секцию YouTube
	echo "Создаём новую секцию YouTube"
	echo "${SELECTED_STRATEGY}" >>/etc/config/youtubeUnblock
	echo "${URLS}" >>/etc/config/youtubeUnblock
	sleep 1

	case "$idx" in
		1)
			# Стратегия по умолчанию
			# Получаем индекс секции YouTube
			SECTION=$(uci show youtubeUnblock | grep "name='YouTube'" | cut -d. -f2)
			# echo "${SECTION}"
			# Переносим секцию YouTube на первую позицию списка
			uci reorder youtubeUnblock.${SECTION}=1
			uci commit
			sleep 1
		;;
	esac
	
	# Запускаем сервисы
	echo "Запускаем сервисы"
	for service in $SERVICES_START; do
	  service $service start >/dev/null 2>&1
	  service $service enable >/dev/null 2>&1
	done
	service dnsmasq restart >/dev/null 2>&1
}

u_section_delete() {

	# Меняем конфиг ЮАБ на конфиг от zapret и правим настройки
	# Удаляем секцию YouTube
	# uci delete youtubeUnblock.$(uci show youtubeUnblock | grep "name='YouTube'" | cut -d. -f2) && uci commit
	section_id=$(uci show youtubeUnblock | grep "name='YouTube'" | cut -d. -f2)

	# Проверяем, что section_id не пустой
	if [ -n "$section_id" ]; then
		echo "Удаляем секцию YouTube: $section_id"
		uci delete youtubeUnblock.$section_id
		sleep 1
		uci commit
	else
		echo "Секция YouTube не найдена"
	fi
}




# Объявляем и инициализируем переменные
# Стратегия по умолчанию
STRATEGY_1="config section
	option name 'YouTube'
	option enabled '1'
	option tls_enabled '1'
	option fake_sni '1'
	option faking_strategy 'pastseq'
	option fake_sni_seq_len '1'
	option fake_sni_type 'default'
	option frag 'tcp'
	option frag_sni_reverse '1'
	option frag_sni_faked '0'
	option frag_middle_sni '1'
	option frag_sni_pos '1'
	option seg2delay '0'
	option fk_winsize '0'
	option synfake '0'
	option sni_detection 'parse'
	option all_domains '0'
	option quic_drop '0'
	option udp_mode 'fake'
	option udp_fake_seq_len '6'
	option udp_fake_len '64'
	option udp_filter_quic 'disabled'
	option udp_faking_strategy 'none'"


STRATEGY_2="config section
	option name 'YouTube'
	option enabled '1'
	option tls_enabled '1'
	option fake_sni '0'
	option faking_strategy 'pastseq'
	option fake_sni_seq_len '1'
	option fake_sni_type 'default'
	option frag 'tcp'
	option frag_sni_reverse '1'
	option frag_sni_faked '0'
	option frag_middle_sni '1'
	option frag_sni_pos '1'
	option seg2delay '0'
	option fk_winsize '0'
	option synfake '0'
	option sni_detection 'parse'
	option all_domains '0'
	option quic_drop '0'
	option udp_mode 'fake'
	option udp_fake_seq_len '6'
	option udp_fake_len '64'
	option udp_filter_quic 'disabled'
	option udp_faking_strategy 'none'"
	
STRATEGY_3="config section
	option name 'YouTube'
	option enabled '1'
	option tls_enabled '1'
	option fake_sni '0'
	option faking_strategy 'pastseq'
	option fake_sni_seq_len '1'
	option fake_sni_type 'default'
	option frag 'tcp'
	option frag_sni_reverse '1'
	option frag_sni_faked '0'
	option frag_middle_sni '1'
	option frag_sni_pos '1'
	option seg2delay '0'
	option fk_winsize '0'
	option synfake '0'
	option sni_detection 'parse'
	option all_domains '0'
	option quic_drop '1'
	option udp_mode 'fake'
	option udp_fake_seq_len '6'
	option udp_fake_len '64'
	option udp_filter_quic 'disabled'
	option udp_faking_strategy 'none'"

STRATEGY_4="config section
	option name 'YouTube'
	option tls_enabled '1'
	option fake_sni '1'
	option faking_strategy 'pastseq'
	option fake_sni_seq_len '5'
	option fake_sni_type 'random'
	option frag 'tcp'
	option seg2delay '3'
	option synfake '0'
	option all_domains '0'
	option sni_detection 'parse'
	option quic_drop '1'
	option enabled '1'
	option frag_sni_reverse '1'
	option frag_sni_faked '0'
	option frag_middle_sni '1'
	option frag_sni_pos '1'
	option fk_winsize '0'"
	
STRATEGY_5="config section
	option name 'YouTube'
	option enabled '1'
	option tls_enabled '1'
	option fake_sni '1'
	option faking_strategy 'randseq'
	option fake_sni_seq_len '5'
	option fake_sni_type 'default'
	option frag 'ip'
	option seg2delay '3'
	option synfake '0'
	option sni_detection 'parse'
	option all_domains '0'
	option quic_drop '0'
	option udp_mode 'fake'
	option udp_fake_seq_len '6'
	option udp_fake_len '64'
	option udp_filter_quic 'all'
	option udp_faking_strategy 'none'
	option udp_stun_filter '0'"
	
STRATEGY_6="config section
	option name 'YouTube'
	option enabled '1'
	option tls_enabled '1'
	option fake_sni '1'
	option faking_strategy 'randseq'
	option fake_sni_seq_len '2'
	option fake_sni_type 'default'
	option frag 'tcp'
	option seg2delay '0'
	option synfake '0'
	option sni_detection 'parse'
	option all_domains '0'
	option quic_drop '0'
	option udp_mode 'fake'
	option udp_fake_seq_len '6'
	option udp_fake_len '64'
	option udp_filter_quic 'all'
	option udp_faking_strategy 'none'
	option udp_stun_filter '0'
	option fake_seq_offset '0'
	option frag_sni_reverse '1'
	option frag_sni_faked '0'
	option frag_middle_sni '1'
	option frag_sni_pos '1'
	option fk_winsize '0'"
  
STRATEGY_7="config section
	option name 'YouTube'
	option enabled '1'
	option tls_enabled '1'
	option fake_sni '1'
	option faking_strategy 'tcp_check'
	option fake_sni_seq_len '1'
	option fake_sni_type 'random'
	option frag 'tcp'
	option frag_sni_reverse '1'
	option frag_sni_faked '0'
	option frag_middle_sni '1'
	option frag_sni_pos '1'
	option seg2delay '3'
	option fk_winsize '0'
	option synfake '0'
	option sni_detection 'parse'
	option all_domains '0'
	option quic_drop '0'
	option udp_mode 'fake'
	option udp_fake_seq_len '6'
	option udp_fake_len '64'
	option udp_filter_quic 'all'
	option udp_faking_strategy 'none'
	option udp_stun_filter '0'"
	
STRATEGY_8="config section
	option name 'YouTube'
	option enabled '1'
	option tls_enabled '1'
	option fake_sni '1'
	option faking_strategy 'tcp_check'
	option fake_sni_seq_len '1'
	option fake_sni_type 'default'
	option frag 'none'
	option seg2delay '0'
	option synfake '0'
	option sni_detection 'parse'
	option all_domains '0'
	option quic_drop '0'
	option udp_mode 'fake'
	option udp_fake_seq_len '6'
	option udp_fake_len '64'
	option udp_filter_quic 'all'
	option udp_faking_strategy 'none'
	option udp_stun_filter '0'"
	

URLS="	list sni_domains 'googlevideo.com'
	list sni_domains 'youtubei.googleapis.com'
	list sni_domains 'ytimg.com'
	list sni_domains 'yt3.ggpht.com'
	list sni_domains 'yt4.ggpht.com'
	list sni_domains 'youtube.com'
	list sni_domains 'youtubeembeddedplayer.googleapis.com'
	list sni_domains 'ytimg.l.google.com'
	list sni_domains 'jnn-pa.googleapis.com'
	list sni_domains 'youtube-nocookie.com'
	list sni_domains 'youtube-ui.l.google.com'
	list sni_domains 'yt-video-upload.l.google.com'
	list sni_domains 'wide-youtube.l.google.com'
	list sni_domains 'youtu.be'
	list sni_domains 'youtube.googleapis.com'
	list sni_domains 'yt.be'
	list sni_domains 'withyoutube.com'
	list sni_domains 'youtubeeducation.com'
	list sni_domains 'youtubefanfest.com'
	list sni_domains 'youtubegaming.com'
	list sni_domains 'youtubekids.com'
	list sni_domains 'youtubemobilesupport.com'"

echo
echo "ПРОВЕРЯЙТЕ ДОСТУП К ЮТУБ"
echo

while true; do

clear

# Выбор стратегии
echo "
	
Выберите стратегию:

 1 - Стратегия по умолчанию (из коробки)
 
 2 - Стратегия pastseq_1
 3 - Стратегия pastseq_2
 4 - Стратегия pastseq_3
 5 - Стратегия randseq_1
 6 - Стратегия randseq_2
 7 - Стратегия tcp_check_1
 8 - Стратегия tcp_check_2
 "
if [ -n "$PODKOP_VERSION" ]; then echo " 9 - Ничего не помогло. Хочу ютуб через podkop!"; fi
echo " 0 - Выход
"


	echo "Введите номер выбранной стратегии"
	printf "> "
	read idx
	echo

	case "$idx" in
		0)
			# Если пользователь ввел 0 — выходим без ошибки
			echo "Выход..."
			echo
			exit 0 
			;;
#		''|*[!0-9]*) 
#			# Проверка на "не число" или пустоту
#			echo "Ошибка: введите номер стратегии"; exit 1 
#			;;
		 9)			
			if [ -n "$PODKOP_VERSION" ]; then
				u_section_delete
				sh <(wget -qO- "https://raw.githubusercontent.com/kkkkCampbell/trash/refs/heads/uttoobe/u_to_podkop")
				exit 0
			 fi
			;;
		*) 
			# Все остальные варианты (числа 1, 2, 3...9)
				if echo "$idx" | grep -qE '^[0-9]$'; then
					eval "SELECTED_STRATEGY=\$STRATEGY_$idx"
					main

					echo

					echo "ПРОВЕРЯЙТЕ ДОСТУП К ЮТУБ"
					echo -e "\033[33mСМЕНИВ СТРАТЕГИЮ КАЖДЫЙ РАЗ ЗАПУСКАЙТЕ НОВЫЙ ВИДЕОРОЛИК ДЛЯ ПРОВЕРКИ\033[0m"
					echo -e "\033[33mВ НЕКОТОРЫХ СЛУЧАЯХ ТРЕБУЕТСЯ ПЕРЕЗАПУСК ЮТУБ-СМОТРЕЛКИ\033[0m"
					echo
					echo "Выбрана стратегия №" "$idx"
					printf "ЕСЛИ СТРАТЕГИЯ СРАБОТАЛА ВВЕДИТЕ 1, ЕСЛИ НЕТ 0 > "
					read strat_working

					if [ "$strat_working" = "1" ]; then
						echo "Успех! Завершаем работу."
						echo
						exit 0
					fi
				fi
			;;
	esac
done

exit 0
